### ISSUE TITLE
Add support for tracking analytics

### ISSUE THREAD

**Issue by pmuir** [cloudmosaic/quickstarts#13]
Allow sending track events (with useful metadata) when the user performs an action in the quick start.

Will likely need some abstraction to cope with plugging in different (or no) library.

**Comment by jgiardino** [comment]
To support tracking, we need to be able to target specific elements in the UI. Elements can be targetted using a subset of CSS selectors. Parent-child selectors are supported, along with `.classname` selectors and using custom data- attributes. For a similar use case, we're using the format `data-testid="contextDescription-elementDescription"`. For example, `data-testid="modalCreate-buttonSubmit"`.

Currently, there are no attributes associated with elements in the quick starts dom that allow us to uniquely target elements, like the "Start the tour" button, or the Next and Back buttons in the drawer. 

For the quick start catalog, we should be able to target these items by adding the data- attributes to the following items:
- Card - Identify which quick start is described by the card, maybe with a short name of the quick start, e.g. `data-testid="card-gettingStarted"`. Should be at a parent level for the card that contains the actions.
- Card actions - Identifies which action. Combined with the previous selector, these don't need to be unique, but can just describe the button, e.g. `data-testid="cardAction-start"`
- Drawer - Identify which quick start is presented in the drawer, e.g. `data-testid="drawer-gettingStarted"`. Should be at a parent level that contains the actions
- Drawer - Identify which step. Can be on the same element as the data- attribute that describes the quick start. These can be concatenated like CSS selectors.
- Drawer actions - Identify which action. When combined with the two previous selectors, we know what actions are clicked in which step of which quick start. For example:
     `[data-testid="drawer-gettingStarted"][data-testid="drawer-step1"] [data-testid="drawerButton-next"]`

BTW, this is just one suggestion on how to support this. Let me know if there's a better way to do this.
