### ISSUE TITLE
Add support for cards that provide external links

### ISSUE THREAD

**Issue by jgiardino** [cloudmosaic/quickstarts#28]
We would like to include additional cards in our quick start page that provide external links instead of quick starts. To support this additional card type, we'd like to include:
- Per card, ability to provide an external link instead of a quick start
- Per card, an extra label within the card that describes the type of content it represents, e.g.:
  - "Quick start" - for quick starts, this label would be the first label to display in the group of labels
  - "Documentation" - for this type, the duration label should not display
- Section headers within the layout to group cards. Our current design is to group by type, but in the future, this might not be the case (e.g. we might want to group by use case).

Below is an example of our current design. PLEASE NOTE, the label that should be used with the quick start card should be singular `quick start` and not plural as shown below.

![image](https://user-images.githubusercontent.com/21063328/111701261-f1a66400-8810-11eb-85c2-482b33205d67.png)

**Comment by jschuler** [comment]
I'll add support for external link and content type label. Section headers we'll leave out for now, right?

**Comment by jschuler** [comment]
Done
