### ISSUE TITLE
Add ability to selectively pull in search/filtering functionality

### ISSUE THREAD

**Issue by jgiardino** [cloudmosaic/quickstarts#29]
This is related to #28, to include additional card types. 

We would like to be able to pull in the toolbar and search functionality that's currently available:
![image](https://user-images.githubusercontent.com/21063328/111701970-f881a680-8811-11eb-831c-f67ea66cfecc.png)

But given that we are introducing other card types, the Status filter by itself might be confusing unless we also include a Type filter. For now, we're requesting the ability to just pull in the search input and the count that display in the toolbar.

Additionally, to better align with a similar page in a related service, is it possible to adopt the following layout in the page header:

![image](https://user-images.githubusercontent.com/21063328/111702385-907f9000-8812-11eb-8941-3d461811941d.png)

This other page stacks a page section and a toolbar component in their layout, e.g.:
```
<PageSection variant={PageSectionVariants.light}>
  <TextContent>
    <Text component="h1">Resources</Text>
  </TextContent>
</PageSection>
<Toolbar>...</Toolbar>
```

**Comment by jschuler** [comment]
Done
